### ISSUE TITLE
Compile error in Arduino Studio for ESP32

### ISSUE THREAD

**Issue by veitk** [marcmerlin/Neopixel-IR#1]
i can't compile your code in arduino studio 1.8.5 ....

D:\Dokumente\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:31:45: error: call to 'failed_compile_time_assert' declared with attribute error: (Cannot use SET_PERI_REG_MASK for DPORT registers use DPORT_SET_PERI_REG_MASK)

                 failed_compile_time_assert();                                                   \

                                             ^

D:\Dokumente\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:145:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

D:\Dokumente\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:236:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((reg), SET_PERI_REG_MASK);                                                             \

             ^

sketch\esp32_ws2812.cpp:229:3: note: in expansion of macro 'SET_PERI_REG_MASK'

   SET_PERI_REG_MASK(DPORT_PERIP_CLK_EN_REG, DPORT_RMT_CLK_EN);

   ^

exit status 1

**Comment by marcmerlin** [comment]
howdy, I realize that you got those errors while trying to build my code, but none of those errors are actually linked to my code :)
Looks like you're using windows with some other version of the esp32 arduino libraries than I am, and honestly I can't help you debug that.
You should get basic FastLED and try to compile a very simple example like demoreel100. I'm pretty certain that you'll get the same error.
I would ask for help from the esp32 folks who provided the windows build you're using as it seems that your first error is there.
If you get FastLED code building and working and then you get errors with my code again, please re-open and I'll see if I can help.
